#!/bin/bash

centos=`cat /etc/os-release | grep -w "centos"`
debian=`cat /etc/os-release | grep -w "Debian"`
fedora=`cat /etc/os-release | grep -w "fedora"`
ubuntu=`cat /etc/os-release | grep -w "Ubuntu"`
openSUSE=`cat /etc/os-release | grep -w "opensuse-leap"`
SLE=`cat /etc/os-release | grep -w "sles"`



if [ "$centos" == "centos" ];then
	echo "This Procedures For centOS 7"
	cd /etc/yum.repos.d/

	sudo wget https://download.opensuse.org/repositories/security:zeek/CentOS_7/security:zeek.repo

	sudo yum install zeek-lts -y

	## TODO : check software Installed Successfully
	echo "Zeek Installed Successfully"

elif [ "$debian" == "debian" ];then
	version11=`cat /etc/os-release | grep -w 'VERSION_ID="11"'`
	version12=`cat /etc/os-release | grep -w 'VERSION_ID="12"'`

	if [ "$version11" == "VERSION_ID='11'" ];then
		echo "Start Install Zeek on Debian 11"
		echo 'deb http://download.opensuse.org/repositories/security:/zeek/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
		curl -fsSL https://download.opensuse.org/repositories/security:zeek/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
		sudo apt update
		sudo apt install zeek-lts -y
		sleep 2
		echo "Zeek Installed Successfully on Debian 11"

	elif [ "$version12" == "VERSION_ID='12'" ];then
		echo 'deb http://download.opensuse.org/repositories/security:/zeek/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
		curl -fsSL https://download.opensuse.org/repositories/security:zeek/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
		sudo apt update
		sudo apt install zeek-lts -y
		echo "Zeek Installed Successfully on Debian 12"
	else
		echo "Sorry.This Version is Not Supported"
	fi

elif [ "$fedora" == "fedora" ];then

	version_id_37=`cat /etc/os-release | grep -w 'VERSION_ID=37'`
	version_id_38=`cat /etc/os-release | grep -w 'VERSION_ID=38'`

	if [ "$version_id_37" == "VERSION_ID=37" ];then
		sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/security:zeek/Fedora_37/security:zeek.repo

		sudo dnf install zeek-lts -y
	

	elif [ "$version_id_38" == "VERSION_ID=38" ];then
		sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/security:zeek/Fedora_38/security:zeek.repo
		sudo dnf install zeek-lts -y
	else 
		echo "Sorry.This Version is Not Supported"
	fi

elif [ "$ubuntu" == "$Ubuntu" ];then
	
	echo "Start Install Zeek on Ubuntu"
	
	version_id_20=`cat /etc/os-release | grep -w 'VERSION_ID=20.04'`
	version_id_22=`cat /etc/os-release | grep -w 'VERSION_ID=22.04'`
	version_id_23=`cat /etc/os-release | grep -w 'VERSION_ID=23.04'`
	if [ "$version_id_22" == 'VERSION_ID="22.04"' ];then
		echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
		curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
		sudo apt update
		sudo apt install zeek-lts -y

	elif [ "$version_id_23" == 'VERSION_ID="23.04"' ];then
	
		echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_23.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
		curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_23.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
		sudo apt update
		sudo apt install zeek-lts -y

	elif [ "$version_id_20" == 'VERSION_ID="20.04"' ];then

		echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
		curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
		sudo apt update
		sudo apt install zeek-lts -y

	fi


elif [ "$openSUSE" == "opensuse-leap" ];then
	check_version=`cat /etc/os-release | grep -w '15.5'`

	if [ "$check_version" == "15.5" ];then
		sudo zypper addrepo https://download.opensuse.org/repositories/security:zeek/15.5/security:zeek.repo
		sudo zypper refresh
		sudo zypper -n install zeek-lts
	fi

elif [ "$SLE" == "sles" ];then
	sudo zypper addrepo https://download.opensuse.org/repositories/security:zeek/openSUSE_Leap_15.4/security:zeek.repo
	sudo zypper refresh
	sudo zypper install -n zeek-lts

fi




